version: "3"

services:
  server:
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/challenge
    links:
      - db

  db:
    image: postgres
    ports:
      - "5431:5432"
    networks:
      - backend
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

networks:
  backend: